# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='service/imgs/')),
                ('description', models.TextField(blank=True, verbose_name='Description du service')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeproj', models.CharField(db_index=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeserv', models.CharField(db_index=True, max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zone',
        ),
        migrations.AddField(
            model_name='localite',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FindImmo.Zone'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/imgs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='products/imgs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='action_type',
            field=models.CharField(blank=True, choices=[('LOCATION', 'LOCATION'), ('VENTE', 'VENTE')], default='LOCATION', help_text='Vente/Location', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Decrire votre rechecher svp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nbChambre',
            field=models.PositiveIntegerField(verbose_name='Nombre Chambre(s)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nbDouche',
            field=models.PositiveIntegerField(verbose_name='Nombre Douches(s)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Prix à partir de'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindImmo.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quartier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ville',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Dealer',
        ),
        migrations.DeleteModel(
            name='TypeImmo',
        ),
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindImmo.Vendor'),
        ),
        migrations.AddField(
            model_name='service',
            name='typeservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tservice', to='FindImmo.TypeService'),
        ),
    ]
