# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0002_auto_20190327_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='project/imgs/')),
                ('description', models.TextField(blank=True, verbose_name='Description du project')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindImmo.Vendor')),
                ('typeproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tproject', to='FindImmo.TypeProject')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='commdt',
            field=models.CharField(blank=True, choices=[('VIDE', 'VIDE'), ('MEUBLE', 'MEUBLE')], default='VIDE', help_text='Vide/meuble', max_length=10),
        ),
    ]
