# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-19 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0003_auto_20190327_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Precisez un detail', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='FindImmo.Commodite'),
        ),
    ]
