# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0004_auto_20190419_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodite',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
