# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-19 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0005_commodite_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodite',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='commodite',
            name='slug',
            field=models.SlugField(default='commodite', max_length=200, unique=True),
        ),
    ]
