# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0007_auto_20190419_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.ManyToManyField(help_text='Select a genre for this book', related_name='commodite', to='FindImmo.Commodite'),
        ),
    ]
