# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FindImmo', '0008_auto_20190422_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='action_type',
            field=models.CharField(blank=True, choices=[('LOCATION', 'LOCATION'), ('VENTE', 'VENTE')], default='LOCATION', help_text='Vente/Location', max_length=10, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='product',
            name='commdt',
            field=models.CharField(blank=True, choices=[('VIDE', 'VIDE'), ('MEUBLE', 'MEUBLE')], default='VIDE', help_text='Vide/meuble', max_length=10, verbose_name='Intérieur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FindImmo.Localite', verbose_name='localité'),
        ),
    ]
